name: Bug
description: Something is broken
labels: ['type:bug']
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      value: |
        1.
  - type: dropdown
    id: device
    attributes:
      label: Device
      options:
        - Desktop
        - Phone
        - Both
